name: Growler
author: sppericat
category: Interface
tags: [growl, notifications]
docs: http://github.com/stephanepericat/Growler/blob/master/README.md
demo: http://sppericat.kodingen.com/demos/growler/ 